### ISSUE TITLE
Add spreadsheet course authoring docs

### ISSUE THREAD

**Issue by richierocks** [datacamp/authoring#103]
Based upon

https://docs.google.com/document/d/1Tk3URwkiFEMR9h1P0rbEdFDJLYEwnPLfGDPTvfpoSHE/edit

**Comment by vincentvankrunkelsven** [comment]
Back from vacation!

I'm working on this here: https://github.com/datacamp/authoring/tree/spreadsheets

**Comment by richierocks** [comment]
draft content is in here; calling it fixed
