### ISSUE TITLE
Add Documentation on Writing Requirements in Authoring

### ISSUE THREAD

**Issue by Robert-cabral** [datacamp/authoring#113]
We should have information for instructors, especially open-course instructors, on writing requirements files.

**For context, here is a note from one open-course instructor:** 
"Hi! I'm trying to make a course with Nipype and I'm curious what is the best way to make user defined environment variables that python will recognize. Nipype is essentially a wrapper for neuroimaging tools that are installed/accessible via the commandline. With a Dockerfile I can use the `ENV` keyword, but since I'm restricted to having my changes in `requirements.sh`, I'm wondering what's the best method to get the docker container to recognize environment variables."

**Comment by filipsch** [comment]
@richierocks writing `requirements.r` files is not SCT terriorty. Let's discuss.

**Comment by filipsch** [comment]
@Robert-cabral after discussing on Slack, this seems to be resolved. We're continuing the discussion here: https://github.com/datacamp/authoring/issues/142.
