### ISSUE TITLE
Step 5: unclear what is covered in one video in the outline

### ISSUE THREAD

**Issue by gvwilson** [datacamp/authoring#13]
@LoreDirick commented on [Thu Sep 28 2017](https://github.com/datacamp/example-course-specs/issues/22)

What seems a bit weird to me in the listed outline is that it is unclear what is covered in one video and what is covered in another one. What I like about the current outline structure is exactly that: I tell my instructors that "main" bullets are a video, and "sub" bullets add extra details to the video and the exercises that follow if that is something the instructor already gives more details on. Also, as a CL, I don't know from this outline how many videos will be in each chapter, and if the instructor is not trying to put too much in one video.

---

@yashasroy commented on [Fri Sep 29 2017](https://github.com/datacamp/example-course-specs/issues/22#issuecomment-333119023)

I agree. I think this stems from the fact that these are example course specs for a course that does _not_ contain videos. I think the idea going forward is that it will be down to the CD and the instructor to figure out how many videos will be in each chapter (and what to cover in them), with the formative assessments being used for guidance.

This is related to https://github.com/datacamp/example-course-specs/issues/9 and https://github.com/datacamp/example-course-specs/issues/12.

---

@gvwilson commented on [Mon Oct 02 2017](https://github.com/datacamp/example-course-specs/issues/22#issuecomment-333666940)

Please close if the revised wording makes this clearer.

**Comment by gvwilson** [comment]
@yasharoy is the wording good enough?

**Comment by richierocks** [comment]
wording and guidance on videos is clearer now.
