### ISSUE TITLE
Add best practices for how to use comments in DataCamp exercises

### ISSUE THREAD

**Issue by yashasroy** [datacamp/authoring#148]
The docs are currently missing best practices on how to write good comments in exercises. This is something that first-time instructors are often confused by, as comments in DataCamp exercises are not like comments in general coding.

My explanation for comments in DataCamp exercises is that they are abbreviated instructions. Some common mistakes made by instructors include:

- Verbose comments (sometimes just copy-pasted from the instructions).
- Including backticks in comments.
- Using only lowercase comments.

There are other subtleties as well, such as when to include the variable name that the result must be assigned to, and when not to.

**Comment by richierocks** [comment]
I think the main rules are

- Write in sentence case.
- Stay under 60 characters (for students on small screens).
- It's OK to abbreviate your grammar.
- Write plain text, not markdown (in particular, don't wrap variable names in backticks).
- Usually comments should have a 1 to 1 match with instructions.

**Comment by richierocks** [comment]
We need a page in here:

https://authoring.datacamp.com/courses/exercises/all-exercise-types/

I'll try and dig out some examples of really good comments (if that's a thing).

**Comment by richierocks** [comment]
fixed: this is in the style guide
