### ISSUE TITLE
add FAQs entry about API calls

### ISSUE THREAD

**Issue by adrian-datacamp** [datacamp/authoring#167]
http://authoring.datacamp.com/faq/

## Background 
It is not uncommon that instructors want to run API calls to download data from somewhere. This is not advisable because
- if the API host servers go down, students won't be able to complete their DataCamp exercise
- if the API host servers are slow, DataCamp exercise could be really slow
- if the API changes after you've built your course, we'd need to rebuild that lesson
- if too many DataCamp students are issuing API calls at the same time, our servers could go down

## Suggestion
@richierocks suggested including an entry on Authoring FAQs where we can tell instructors that they shouldn't use APIs, and potentially also our workarounds to them.

**Comment by richierocks** [comment]
This exists here https://instructor-support.datacamp.com/frequently-asked-questions-faq/datasets/using-web-apis

**Comment by adrian-datacamp** [comment]
@richierocks, thanks for the article! Do you think it should explicitly mention workaround options?
