### ISSUE TITLE
Have instructors differentiate data sources

### ISSUE THREAD

**Issue by gvwilson** [datacamp/authoring#18]
From @ismayc on Slack:

Looking over outline feedback (in the old course specs system), I'm wondering if it makes sense to have instructors clearly differentiate the data sources they plan to use in the slides/videos and those they plan to use in the exercises in the new course specs. It seems that when instructors have a good sense for this the course development goes a lot faster/easier.

**Comment by gvwilson** [comment]
@ismayc now that you have worked with the spec, do you still think this is an issue?

**Comment by ismayc** [comment]
@gvwilson Yes, I think so. Ultimately, I think the Content Developers have a better sense for this though. (cc @yashasroy)

**Comment by richierocks** [comment]
I think this can be done simply by listing it as a "Good idea" on the Design Datasets page.

https://authoring.datacamp.com/courses/design/brainstorming-datasets.html

@beccarobins Since you're reworking that page; I'll assign you.

**Comment by richierocks** [comment]
fixed
