### ISSUE TITLE
Links to Content Guidelines are not working

### ISSUE THREAD

**Issue by yashasroy** [datacamp/authoring#202]
@richierocks The following links are all returning 404s for me:

http://authoring.datacamp.com/courses/exercises/normal-exercises/courses/guidelines/content.html
http://authoring.datacamp.com/courses/exercises/normal-exercises/courses/guidelines/
http://authoring.datacamp.com/courses/exercises/normal-exercises/courses/spreadsheets/exercises/content-guidelines.html

Can this please be fixed?

**Comment by richierocks** [comment]
I'm closing this since authoring has been abandoned.
