### ISSUE TITLE
Add heuristic on judging difficulty level

### ISSUE THREAD

**Issue by richierocks** [datacamp/authoring#93]
I got a good quote from instructor Melinda Higgins.

> When designing introductory courses, if you are bored to tears with the material, you've probably pitched it at the right level. If you find it interesting, it's too hard.

This feels like it belongs in the documentation somewhere. (Course design step 3?)

**Comment by justmytwospence** [comment]
The yang to this pedagogical yin would be @gvwilson's "Nobody will be more excited about the lesson than you are." But I'm not opposed to making this point in the docs if you feel instructors are failing in the direction of complication overwhelmingly.
