### ISSUE TITLE
No mention of 5 multiple choice exercise limit in course?

### ISSUE THREAD

**Issue by ismayc** [datacamp/authoring#98]
Doesn't appear that there is a mention of not having back-to-back multiple choice exercises either. I think given the discussion Greg led on good multiple choice exercises, we should revisit both of these pseudo-guidelines anyway. I'm going to proceed with instructors assuming these are not strict guidelines since they aren't included here.

**Comment by richierocks** [comment]
Addressed in https://github.com/datacamp/authoring/pull/136
